//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackAttachment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string MimeType { get; set; }
        public Nullable<int> FeedbackId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> Iden { get; set; }
        public byte[] FileContent { get; set; }
    
        public virtual Feedback Feedback { get; set; }
    }
}
