//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int Id { get; set; }
        public Nullable<int> FeedbackId { get; set; }
        public Nullable<int> UserSolveId { get; set; }
        public string solutions { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Status { get; set; }
    
        public virtual Feedback Feedback { get; set; }
    }
}
